### I have created this notebook to practice python and pandas problems

#### Problem 1
Write a function clean_name(name) that strips whitespace and returns Title Case — test it on " ali RAZA ".

In [3]:
def clean_name(name):
    list_of_name = name.split(" ")
    result = ""
    for item in list_of_name:
        result += item.capitalize()
    return result
print(clean_name("ali Raza "))

AliRaza

#### Problem 2
Given marks = [45, 72, 88, 91, 33, 67], use a list comprehension to get only the passing marks (≥ 50).

In [5]:
marks = [45, 72, 88, 91, 33, 67]
greater = [x for x in marks if x>= 50]
print(greater)

[72, 88, 91, 67]

#### Problem 3
Build a dictionary that counts how many times each letter appears in "pandas" — without using collections.Counter.

In [6]:
word = "pandas"
count={}
for w in word:
    if w in count:
        count[w] += 1
    else:
        count[w] = 1
print(count)

{'p': 1, 'a': 2, 'n': 1, 'd': 1, 's': 1}

#### Problem 4
Write a function with *args that returns both the minimum and maximum of any number of arguments as a tuple.

In [14]:
def minMax(*numbers):
    min=numbers[0]
    max = numbers[-1]
    for number in numbers:
        if number <= min:
            min = number
        elif number >= max:
            max = number
    return (min,max)
TminMax = minMax(45, 72, 88, 91, 33, 67)
print(f"Minimum:{TminMax[0]}")
print(f"Maximum:{TminMax[1]}")

Minimum:33
Maximum:91

#### Problem 5
Use map() and filter() together (one line) to get the squares of only the even numbers from 1–20.

In [17]:
nums = [x for x in range(1,21)]
squareOfEvens = list(map(lambda x : x**2,filter(lambda y : y%2 ==0,nums)))
print(squareOfEvens)

[4, 16, 36, 64, 100, 144, 196, 256, 324, 400]

#### Problem 6
Open a file, write 3 lines to it, then read it back and print the line count — all using with open(...).

In [25]:
outFile = open("file.txt","w")
outFile.write("Hi,My Name is Saad\n")
outFile.write("I am a Developer\n")
outFile.write("I love coding")
outFile.close()
inFile = open("file.txt","r")
for line in inFile:
    print(line)

Hi,My Name is Saad

I am a Developer

I love coding

#### Problem 7
Wrap a risky int("abc") conversion in try/except and print a friendly message instead of crashing.

try:
    userInput = int(input("Enter a number"))
    print(userInput)
except:
    print("Please enter a valid number")

## Pandas Problem

In [113]:
## Before doing any important code we will import some libraries 
import pandas as pd
import numpy as np
import random as rd

### Problem 1
Create a Series of 5 cities with their populations as the index values' labels; use .loc to get one city and .iloc to get the 3rd one by position.

In [43]:
cities = pd.Series([1000000,2034520,5043132,987342,4539100],index = ["Dera Ismail Khan","Lahore","Karachi","Islamabad","Peshawar"])
print(cities.loc['Lahore'])
print(cities.iloc[2])

2034520
5043132

### Problem 2
Build the same DataFrame two different ways — once from a dict of lists, once from a list of dicts — and prove they're equal with .equals().

In [94]:
dictOfLists = {
    "Dera Ismail Khan":[1800,1200384,234052], #Founded in , population,area in sq km
    "Lahore":[1830,4352152,340981],
    "Karachi":[1503,6028418,40285345]
}
ListOfDicts = [
    {city:dictOfLists[city][0] for city in dictOfLists },
     
    {city:dictOfLists[city][1] for city in dictOfLists },
    
    {city:dictOfLists[city][2] for city in dictOfLists }
]
DfDictOfLists = pd.DataFrame(dictOfLists)
DfListOfDicts = pd.DataFrame(ListOfDicts)
print(DfDictOfLists)
print(DfListOfDicts)
DfDictOfLists.equals(DfListOfDicts)

   Dera Ismail Khan   Lahore   Karachi
0              1800     1830      1503
1           1200384  4352152   6028418
2            234052   340981  40285345
   Dera Ismail Khan   Lahore   Karachi
0              1800     1830      1503
1           1200384  4352152   6028418
2            234052   340981  40285345

True

### Problem 3
Given a DataFrame of students with a marks column, add a new column grade using np.where or .apply() with a custom function.

In [117]:
def applyGrade(marks):
    if marks>=90 and marks<=100:
        return 'A+'
    elif marks>=80 :
        return 'A'
    elif marks>=70:
        return 'B' 
    elif marks>=60:
        return 'C'
    elif marks>=50:
        return 'D'
    else:
        return 'F'
names = ['Saad','Shahid','Hassan','Abdullah','Zamam','Hanan']
departments = ['BCS','BAI','BSE','BCS','BAI','BCS']
cgpas = [3.6,2.3,2.3,3.8,2,1.6]
DfStudents = pd.DataFrame({"Names":names,"Marks":marks,"Departments":departments,"CGPA":cgpas})
DfStudents['Grades'] = DfStudents["Marks"].apply(applyGrade)
DfStudents

      Names  Marks Departments  CGPA Grades
0      Saad     45         BCS   3.6      F
1    Shahid     72         BAI   2.3      B
2    Hassan     88         BSE   2.3      A
3  Abdullah     91         BCS   3.8     A+
4     Zamam     33         BAI   2.0      F
5     Hanan     67         BCS   1.6      C

### Problem 4
Select all rows where department == "BCS" and cgpa > 3.0 using a boolean mask, then repeat using .query().

In [185]:
DfStudents[(DfStudents["Departments"] == 'BCS') &  (DfStudents['CGPA'] >= 3.0)]        
DfStudents.query("Departments == 'BCS' and CGPA >=3.0")

      Names  Marks Departments  CGPA Grades
0      Saad     45         BCS   3.6      F
3  Abdullah     91         BCS   3.8     A+